name: "ZeroNorth Scanning"

on:
  push:
  pull_request:
  schedule:
    - cron: '0 18 * * 6'

jobs:
  ZeroNorth-Build:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Zip Project
      run: zip -R project.zip '*.py' '*.html' '*.htm' '*.js' '*.php' 'requirements.txt' '*.json' '*.lock' '*.ts' '*.pl' '*.pm' '*.plx' '*.pl5' '*.cgi' '*.go' '*.sum' '*.mod'
      env:
        build-name: project.zip



  ZeroNorth-Scan:
    runs-on: ubuntu-latest
    container: zeronorth/integration:latest
    steps:
    - name: Run ZN IC
      run: |
        echo "docker run -e POLICY_ID='Ht27RaViRyWCATVfanRbKg' -e INCLUDE_FILES='project.zip' -e CYBRIC_API_KEY=${{ env.ZN_API_KEY }}"

    - name: ZeroNorth Integration Container
      uses: docker://zeronorth/integration:latest
      with:
        args: -v INCLUDE_FILES='project.zip' -v POLICY_ID='Ht27RaViRyWCATVfanRbKg'
      env: 
          CYBRIC_API_KEY: ${{ env.ZN_API_KEY }}
    - name: NPM Install
      run: |
        npm install

    
