name: "ZeroNorth Scanning"

on:
  push:
  pull_request:
  schedule:
    - cron: '0 18 * * 6'

jobs:
  ZeroNorth-Build:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: ZeroNorth Integration Container
      uses: docker://zeronorth/integration
      with:
        args: --CUSTOMER_ARTIFACTS_PATH './app.ts' --POLICY_ID 'Ht27RaViRyWCATVfanRbKg'
      env: 
          CYBRIC_API_KEY=${{ env.ZN_API_KEY }}
    - name: NPM Install
      run: |
        npm install
    - name: Perform ZeroNorth Analysis
      run: |
        echo "This is zn executing code analysis"



    
