name: "ZeroNorth Scanning"

on:
  push:
  pull_request:
  schedule:
    - cron: '0 18 * * 6'

jobs:
  ZeroNorth-Scan:
    runs-on: ubuntu-latest
    #container: zeronorth/integration:latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Run ZN IC
      run: | 
        ls -la ${{env.GITHUB_WORKSPACE}} && echo ${{env.PWD}} && docker run -e POLICY_ID=Ht27RaViRyWCATVfanRbKg -v ${{env.GITHUB_WORKSPACE}}:/code -v ${{env.GITHUB_WORKSPACE}}:/results -e INCLUDE_FILES=/code/project.zip -e LOG_LEVEL=DEBUG -e CYBRIC_API_KEY=${{ secrets.ZN_API_KEY }} zeronorth/integration:latest ls -la /code
        
    - name: NPM Install
      run: |
        npm install

    
